<a href="https://colab.research.google.com/github/Frknslmn50/EADIR_23L/blob/master/math4afffit_FURKANSALMAN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

copyright 2020: *Władysław Skarbek, Warsaw University of Technology*<br>
(Jupyter notebook addressed to students of: EADIR, GSN, MATMU)
$\newcommand{\xx}[2]{(#1)(#2)}$
$\newcommand{\bb}[1]{\mathbb{#1}}$
$\newcommand{\cl}[1]{\mathcal{#1}}$
$\newcommand{\tp}[1]{{#1}^{\intercal}}$
$\newcommand{\tr}[1]{\text{trace}\left[#1\right]}$
$\newcommand{\inv}[1]{\in\bb{R}^{#1}}$
$\newcommand{\inm}[2]{\in\bb{R}^{#1\times#2}}$
$\newcommand{\invc}[1]{\in\bb{C}^{#1}}$
$\newcommand{\inmc}[2]{\in\bb{C}^{#1\times#2}}$
$\newcommand{\rbox}[2]{\mathrel{\raise{#1}{#2}}}$
$\newcommand{\xconv}[5]{
\begin{array}[]{r}{\tiny{#4\ }}\\\raise{2.5pt}{{\tiny{#3}}}\end{array}
\kern{-4pt}
\begin{array}[]{l}{\LARGE\bb{C}}\kern{-6.5pt}\raise{4.5pt}{{\tiny{#5}}}\end{array}
\kern{0pt}
\begin{array}[]{l}{\tiny {#2}}\\\raise{2.5pt}{{\tiny{#1}}}\end{array}}$
$\newcommand{\xdense}[5]{
\begin{array}[]{r}{\tiny{#4\ }}\\\raise{1.5pt}{{\tiny{#3}}}\end{array}
\kern{-4pt}
\begin{array}[]{l}{\LARGE\bb{F}}\kern{-4.5pt}\raise{1.5pt}{{\tiny{#5}}}\end{array}
\kern{2pt}
\begin{array}[]{l}{\tiny {#2}}\\\raise{1.5pt}{{\tiny{#1}}}\end{array}}$
$\newcommand{\xpool}[5]{
\begin{array}[]{r}{\tiny{#4\ }}\\\raise{1.5pt}{{\tiny{#3}}}\end{array}
\kern{-3pt}
\begin{array}[]{l}{\LARGE\bb{P}}\kern{-6.5pt}\raise{0.8pt}{{\tiny{#5}}}\end{array}
\kern{0pt}
\begin{array}[]{l}{\tiny {#2}}\\\raise{1.5pt}{{\tiny{#1}}}\end{array}}$
$\newcommand{\xinp}[5]{
\begin{array}[]{r}{\tiny{#4\ }}\\\raise{1.5pt}{{\tiny{#3}}}\end{array}
\kern{-4pt}
\begin{array}[]{l}{\LARGE\cl{I}}\kern{-4.5pt}\raise{1.5pt}{{\tiny{#5}}}\end{array}
\kern{2pt}
\begin{array}[]{l}{\tiny {#2}}\\\raise{1.5pt}{{\tiny{#1}}}\end{array}}$
$\newcommand{\xdrop}[5]{
\begin{array}[]{r}{\tiny{#4\ }}\\\raise{1.5pt}{{\tiny{#3}}}\end{array}
\kern{-4pt}
\begin{array}[]{l}{\LARGE\bb{D}}\kern{-4.5pt}\raise{1.5pt}{{\tiny{#5}}}\end{array}
\kern{0.5pt}
\begin{array}[]{l}{\tiny {#2}}\\\raise{1.5pt}{{\tiny{#1}}}\end{array}}$
$\newcommand{\xmerge}[5]{
\begin{array}[]{r}{\tiny{#4\ }}\\\raise{1.5pt}{{\tiny{#3}}}\end{array}
\kern{-4pt}
\begin{array}[]{l}{\LARGE\bb{M}}\kern{-4.5pt}\raise{1.5pt}{{\tiny{#5}}}\end{array}
\kern{2pt}
\begin{array}[]{l}{\tiny {#2}}\\\raise{1.5pt}{{\tiny{#1}}}\end{array}}$
$\newcommand{\xgeneral}[5]{
\begin{array}[]{r}{\tiny{#4\ }}\\\raise{1.5pt}{{\tiny{#3}}}\end{array}
\kern{-4pt}
\begin{array}[]{l}{\LARGE\bb{Q}}\kern{-9.0pt}\raise{4.5pt}{{\tiny{#5}}}\end{array}
\kern{2pt}
\begin{array}[]{l}{\tiny {#2}}\\\raise{1.5pt}{{\tiny{#1}}}\end{array}}$
$\def\ds{\displaystyle}$
$\def\ass{\leftarrow}$
$\def\od#1#2{\nabla_{#2}#1}$
$\def\tod#1#2{\tp{\nabla}_{#2}{#1}}$
$\def\cl#1{{\cal#1}}$
$\def\sp#1#2{\frac{\partial#1}{\partial#2}}$
$\def\eqd{\doteq}$
$\def\ra{\rightarrow}$
$\def\lra{\longrightarrow}$
$\def\ovra#1{\overset{#1}{\lra}}$
$\def\dra{\overset{\circ}{\lra}}$
$\def\xeq#1{\overset{#1}{=}}$
$\def\ov#1{\overline{#1}}$
$\def\dotp#1#2{\left\langle#1,#2\right\rangle}$
$\def\th#1{\ov{#1}^{\intercal}}$
$\def\rv#1{\widetilde{#1}}$
$\def\vars#1#2{\mathtt{var}_{#1}{\left[#2\right]}}$
$\def\pmodd#1{\kern{-1mm}\pmod{#1}}$
$\def\pdt#1#2#3{\frac{\partial^2 #1}{\partial #2\partial #3}}$
$\def\diag#1{\mathtt{diag}\left[#1\right]}$
$\def\rank#1{\mathtt{rank}\left[#1\right]}$
$\def\tr#1{\mathtt{tr}\left[#1\right]}$


# Mathematics of clouds fitting

###EVD  decomposition

####Eigenvalue definition

For a complex squared matrix $C\inmc{n}{n}$ a *spectrum*
$\lambda(C)\subset\bb{C}$ is defined:
$
\lambda(C) \eqd \{\lambda\in\bb{C}: \det(C-\lambda I_n)=0\}
$
* The function  $p(\lambda)\eqd\det(C-\lambda I_n)$ is *characteristic polynomial* of $C.$ 
* *Matrix spectrum is finite:*:<br>If $C\inmc{n}{n}$ then $\left|\lambda(C)\right|\leq n.$
* Elements of spectrum are called *eigenvalues*: $\lambda\in\lambda(C)$ if and only 
$\exists u\invc{n}, Cu=\lambda u.$
* The vector $u$ scaled with $C$ by $\lambda$ is called *eigenvector* of $C$ wrt $\lambda.$
* Each eigenvalue determines an *eigen-subspace* of eigenvectors:<br>
If $\lambda\in\lambda(C)$ then the set $\cl{E}_{\lambda}\eqd\{u: Cu=\lambda u\}$  is the subspace of $\bb{C}^n.$



In [ ]:
import sympy as sym
x = sym.Symbol('x'); y = sym.Symbol('y')
print(sym.expand((x + y) ** 3))
print(sym.expand((x-1)*(x+1)))

x**3 + 3*x**2*y + 3*x*y**2 + y**3
x**2 - 1


In [ ]:
As = sym.Matrix([[1,2],[3,4]])
xI = sym.Matrix([[x,0],[0,x]])
ex = sym.expand(xI-As); print(ex)
d = ex.det(); print(d)
p = sym.expand(d); print(p)
sym.nroots(p)

Matrix([[x - 1, -2], [-3, x - 4]])
x**2 - 5*x - 2
x**2 - 5*x - 2


[-0.372281323269014, 5.37228132326901]

In [ ]:
import numpy as np
from numpy.linalg import eig, svd, norm, cholesky
A = np.array([[1,-2,3],[-4,5,6],[7,8,-9]])
A, eig(A)

(array([[ 1, -2,  3],
        [-4,  5,  6],
        [ 7,  8, -9]]),
 (array([-13.76691494,   2.78453226,   7.98238268]),
  array([[ 0.23127389,  0.84043331, -0.09343993],
         [ 0.34064779,  0.05826955,  0.91498738],
         [-0.91130208,  0.53877315,  0.3925138 ]])))

***Exercise*** Check the eigenvalues in the last example using symbolic computation.

Solution:

In [ ]:
x = sym.Symbol('x');
As = sym.Matrix([[1,-2,3],[-4,5,6],[7,8,-9]])
xI = sym.Matrix([[x,0,0],[0,x,0],[0,0,x]])
ex = sym.expand(xI-As);
d = ex.det();
p = sym.expand(d);
sym.nroots(p)

[-13.7669149364246, 2.78453225678850, 7.98238267963608]

Getting the same results using symbolic notation.

##### Eigenvalue problem for symmetric matrices

 * *Conjugate transposition* $\th{C}$ of a complex squared matrix $C$ is defined elementwise: 
$
(\th{C})_{ij}\eqd \ov{C}_{ji},\ i,j=1,\dots,n
$
* $C$ is *Hermitian* if and only if $\th{C}=C.$
* Eigenvalues of symmetric matrix are real numbers:<br>
If $C=\tp{C}$ then $\lambda(C)\subset\bb{R}$
* *Orthogonality of eigenvectors* wrt different eigenvalues:<br>
If $Cu_i=\lambda_i u_i,\ Cu_j=\lambda_j u_j$ and $\lambda_1\neq\lambda_2$ then $\tp{u}_iu_j=0.$
* *Orthogonal eigenvector base*  exists for symmetric matrices:<br> 
Let $\mathtt{obase}(\cl{S})$ denotes any orthogonal base for the subspace $\cl{S}.$<br> 
Then
$\ds
\mathtt{obase}\left(\bb{C}^n\right) \eqd \bigcup_{\lambda\in\lambda(C)}\mathtt{obase}\left(\cl{E}_{\lambda}\right)
$


####Eigenvalue decomposition


Let the eigenvector base established wrt $C\inmc{n}{n}$ be written into columns of matrix $U$ according the decreasing order of eigenvalues:
$$
\begin{array}{l}
Cu_i = \lambda_iu_i,\ i=1,\dots,n\\[5pt]
U \eqd [u_1,\dots,u_n],\ \lambda_1\geq\dots\geq\lambda_n,\ 
\Lambda \eqd \diag{\lambda_1,\dots,\lambda_n}
\end{array}
$$

The *eigenvector matrix* $U$ and *eigenvalue matrix* $\Lambda$ specify EVD (*EigenValue Decomposition*):<br>
Spectral theorem for symmetric $C\inmc{n}{n}:$
$$
C = U\Lambda \tp{U} = \sum_{i=1}^n\lambda_iu_i\tp{u}_i
$$


In [ ]:
B = np.dot(A,A.T)
lambdas,U = eigvals, eigvecs = eig(B)
Lambda = np.diag(lambdas)
print(B, '\n', np.dot(np.dot(eigvecs,np.diag(eigvals)),eigvecs.T))
B-np.dot(np.dot(U,Lambda),U.T)

[[ 14   4 -36]
 [  4  77 -42]
 [-36 -42 194]] 
 [[ 14.   4. -36.]
 [  4.  77. -42.]
 [-36. -42. 194.]]


array([[-1.06581410e-14,  1.90958360e-14, -7.10542736e-15],
       [ 2.04281037e-14,  1.42108547e-14, -1.42108547e-14],
       [-7.10542736e-15, -1.42108547e-14, -8.52651283e-14]])

###SVD by EVD

If $A\tp{A}\overset{evd}{=} U\Lambda\tp{U}$ and $\tp{A}A\overset{evd}{=} V\Lambda\tp{V}$ then $A\overset{svd}{=}U\sqrt{\Lambda}\tp{V}.$

In [ ]:
s2,U = eig(np.dot(A,A.T))
s3,V = eig(np.dot(A.T,A))
print(s2,s3,'\n',U,'\n',V)
UU,s,VVt = svd(A)
print(s*s,'\n',UU,'\n',VVt.T)

[213.8312464   6.8032865  64.3654671] [213.8312464   6.8032865  64.3654671] 
 [[ 0.17517411  0.977064   -0.12107839]
 [ 0.29357441  0.06554757  0.95368631]
 [-0.93974895  0.20260667  0.27535875]] 
 [[-0.51818244 -0.81781672 -0.25032533]
 [-0.43769958  0.00212276  0.89911877]
 [ 0.73478298 -0.57547486  0.35905802]]
[213.8312464  64.3654671   6.8032865] 
 [[ 0.17517411  0.12107839 -0.977064  ]
 [ 0.29357441 -0.95368631 -0.06554757]
 [-0.93974895 -0.27535875 -0.20260667]] 
 [[-0.51818244  0.25032533 -0.81781672]
 [-0.43769958 -0.89911877  0.00212276]
 [ 0.73478298 -0.35905802 -0.57547486]]


###Nonnegatively defined matrices

If $A\inm{n}{n}$ and $\tp{A}=A$ then the nonnegativity is satisfied if and only if $\tp{x}Ax\geq 0$ for all $x\inv{n}.$

###Cholesky decomposition

If $B\inm{n}{n}$ is symmetric and nonnegatively defined then ther exists lower triangular matrix $X\inm{n}{n}$ such that $B=X\tp{X}.$ 

In [ ]:
B = np.dot(A,A.T)
X = cholesky(B) 
print(B,'\n',X,'\n',np.dot(X,X.T))

[[ 14   4 -36]
 [  4  77 -42]
 [-36 -42 194]] 
 [[ 3.74165739  0.          0.        ]
 [ 1.06904497  8.70960061  0.        ]
 [-9.62140471 -3.64130195  9.3898611 ]] 
 [[ 14.   4. -36.]
 [  4.  77. -42.]
 [-36. -42. 194.]]


###Generalized Procrustes problem

The generalized Procrustes problem refers to the optimal matching of the source 3D solid object to the another solid 3D object, when in matching process we can apply any affine transformations.

In applications related to 3D model identification mostly we deal with clouds of 3D points than with solid 3D objects.

In mathematical terms we state the problem as the optimization least square problem:<br>
 having the source cloud of points $C\inm{3}{N}$ and the corresponding target cloud of points $C'\inm{3}{N}$,<br>
 find the rotation matrix $R\inm{3}{3}$, the scaling coefficient $s\in\bb{R}_+$ and the translation vector $b\inv{3}$<br> 
 minimizing the following loss function:
$\boxed{\cl{E}(R,s,b) \eqd \left\|sRC+b\tp{1}_N-C'\right\|^2}$.

The above optimization problem is called *the generalized Procrustes problem*<br> and there is a closed form solution based on *SVD matrix decomposition* <br>
$\ov{C}'\tp{\ov{C}}\overset{svd}{=}U\Sigma\tp{V}$, where $\ov{C}\eqd C-\ov{c}\tp{1}_N$ is the centering operator for the cloud of the points, i.e. such translation of all points to get their centroid  $\ov{c}\eqd\ds\frac{1}{N}\sum_{i\in[N]}c_i,$  to be loacted in the origin of the coordinate system.

#####**Question** (on use of Procrustes name)
Who was Procrustes? Is he really dealt with the above problem?

**Answer**:

In Greek mythology, Procrustes was a bandit who would ambush travelers and force them to fit onto an iron bed. If they were too tall, he would chop off their legs to make them fit, and if they were too short, he would stretch them out. The name "Procrustes" has been used metaphorically to describe any situation where something is forced to fit into a preconceived mold.

In the context of mathematics, the term "Procrustes problem" refers to the task of finding the best transformation that aligns two sets of data. The term is not directly related to the mythological figure, but it is inspired by the idea of forcing something to fit a predetermined shape. The Procrustes problem is a common task in fields such as computer vision and data analysis, where it is often used to align 3D models or to compare datasets.

#####**Exercise (math)** (Loss function - from quadratic norm of affine fit to sum of squared errors)

Let point matrices be detailed by the points $c_i,c'_i$ they represent:
$$C=[c_0,c_1,\dots,c_{N-1}],\quad C'=[c'_0,c'_1,\dots,c'_{N-1}]$$ 
Rewrite the loss function $\cl{E}(R,s,b) \eqd \left\|sRC+b\tp{1}_N-C'\right\|^2$ in the form:
$$
\cl{E}(R,s,b) = \sum_{i=0}^{N-1}\|???-c'_i\|^2 
$$

*Hint:* For any matrix $A\inm{M}{N}$ its squared  norm can be calculted by the summation of squared norms of its all columns:
$$
\left\{
A\eqd[a_0,\dots,a_{N-1}], a_i\inv{M}, i=0,\dots,N-1\right\} \lra \|A\|^2 = \sum_{i=0}^{N-1}\|a_i\|^2
$$

**Solution:**

Applying this hint to the Procrustes loss function, we can express it as:
$$
\cl{E}(R,s,b) = \sum_{i=0}^{N-1}\|sRc_i+b-c'_i\|^2 
$$

###Solution of the generalized Procrustes problem

The following formulas define the optimal solution for clouds of points of any dimension $M$, i.e. the point clouds $C, C'\inm{M}{N}$ are subsets of $\bb{R}^M$:
$$
\ov{C}'\tp{\ov{C}}\overset{svd}{=}U\Sigma\tp{V}
\ds \longrightarrow \left[\ds 
R^{\ast} \ass U\tp{V},\  s^{\ast} \ass \ds
\frac{\tr{\Sigma}}{\tr{\ov{C}\tp{\ov{C}}}}=
\frac{\ds\sum_{i\in[M]}\sigma_i}{\|\ov{C}\|^2},\ b^{\ast} \ass \ov{c}'-s^{\ast}R^{\ast}\ov{c}\right]
$$

*Observation:* The above formulas become true if instead of the outer product $\ov{C}'\tp{\ov{C}}$ for the centered clouds of points, we consider the mutual covariance matrix of those clouds $Cov(C',C)\eqd\frac{1}{N}\ov{C}'\tp{\ov{C}}$, since as the effect of division by $N$,  $\sigma_i'=\frac{\sigma_i}{N}$, and in the same time the normalization constant $\frac{1}{N}$ affects the clouds by the factor $\frac{1}{\sqrt{N}}$:
$$
\begin{array}{l}
Cov(C',C)\eqd\frac{1}{N}\ov{C}'\tp{\ov{C}} = \left(\frac{\ov{C}'}{\sqrt{N}}\right)\left(\frac{\tp{\ov{C}}}{\sqrt{N}}\right)
\overset{svd}{=}U\underbrace{\left(\frac{\Sigma}{N}\right)}_{\Sigma'}\tp{V}\\
\ds \longrightarrow \left[\ds 
R^{\ast} \ass U\tp{V},\  s^{\ast} \ass 
\frac{\tr{\Sigma'}}{\tr{Cov(C,C)}}=
\ds\frac{\ds\sum_{i\in[M]}\frac{1}{N}\sigma_i}{\left\|\frac{1}{\sqrt{N}}\ov{C}\right\|^2}=\frac{\ds\sum_{i\in[M]}\sigma_i}{\|\ov{C}\|^2}\right]
\end{array}
$$

#####**Problem (math)** (Geometric interpretation of SVD matrix factors)

To get a geometric intuition on SVD decomposition for any matrix $A\inm{m}{n}$, consider the image $S'$ of the unit sphere $S(0_n;1)$ under mapping $A:\bb{R}^n\ra\bb{R}^m:$
$$
S'\eqd\{Ax|\ x\inv{n},\ \tp{x}x=1\}
$$ 
You can easily check that $S'$ is symmetric with respect to the zero $0_m\inv{m}$ - the coordinate origin. You can also find in $S'$, the nearest and the furthest points from zero and located on the surface $S'$. Simply, inspect the stationary points of Lagrangian function $L(x,\lambda)=\|Ax\|^2-\lambda\|x\|^2=
\tp{x}(\tp{A}A)x-\lambda\tp{x}x$:
$$
  \od{L(x,\lambda)}{x}=2\tp{A}{A}x-2\lambda x=0_n\lra \tp{A}Ax=\lambda x \text{ and } \|Ax\|^2=\lambda\|x\|^2=\lambda
$$
Hence the furthest point from (nearest point from) zero $0_m$, located on $S'$ is the eigenvector $v_{max}$  ($v_{min}$) of the matrix $\tp{A}A$ corresponding to the biggest $\lambda_{max}$(the least $\lambda_{min}$) eigenvalue. Those vectors can be found from EVD (*eigenvalue decomposition*) of this matrix:
$$
\Lambda=\diag{\lambda_{max},\dots,\lambda_{min}} \lra \tp{A}{A} \overset{evd}{=} V \Lambda \tp{V}
$$

To see the geometric sense of matrix factors, i.e the othogonal matrix $U\inm{m}{m}$, the diagonal  matrix $\Sigma\inm{m}{n}$, and the orthogonal matrix $V\inm{n}{n},$ verify the following implication:
$$
 \tp{U}U=I_m,\ \Sigma=\diag{\sigma_{max},\dots,\sigma_{min}},\ \tp{V}V=I_n,\ 
A\overset{svd}{=}U\Sigma\tp{V} \lra 
\tp{A}A = V\Sigma^2\tp{V}
$$
In the geometric terms, the surface $S'$ is the *hyper-ellipsoid*.

Hence $V$ keeps the half-axes of the ellipsoid $S'$ and $\Sigma$ includes the lengths of those half-axes.

Can you guess how is defined the hyper-ellipsoid $S''$ for which the matrix $U$ keeps its half-axes?


---





####Function `generalProcrustes` 

In [ ]:
def generalProcrustes(C_out,C_in): 
  ucorr = np.dot(C_out,C_in.T)
  U,sigmas,Vt = svd(ucorr); R = np.dot(U,Vt)
  s = np.sum(sigmas)/np.sum(C_in*C_in)
  cp = np.mean(C_out,axis=1); c = np.mean(C_in,axis=1)
  b = cp-s*np.dot(R,c)
  return R,s,b

#####**Exercise** (on testing function `generalProcrustes`)

Let $C\inm{3}{100}$ be a cloud of $n=100$ points in 3D space generated  randomly according to the standard normal distribution. We make a rotation, scaling, and translation (shift) according the following formula: 
$$
c'_i = 
3\cdot
\left[
\begin{array}{ccc}
\frac{\sqrt{3}}{2} & -\frac{1}{2} & 0\\
\frac{1}{2} & \frac{\sqrt{3}}{2} & 0\\
0 & 0 & 1
\end{array}
  \right]
  c_i +
\left[
\begin{array}{c}
1\\
0\\
-1
\end{array}
  \right],\ i=0,\dots,99
$$ 
Check the correctness of procrustes theorem on provided data.

**Solution**

*Define affine transformation*

In [ ]:
s = 3
b = np.array([1,0,-1.])
sq3 = np.sqrt(3)
R = np.array([[sq3/2,-1/2,0],[1/2,sq3/2,0],[0,0,1]])

*Check orthogonality*

In [ ]:
print('Orthogonal?:\n',np.dot(R.T,R))

Orthogonal?:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


It's orthogonal.

*Generate random cloud of points and make centering*

In [ ]:
from numpy.linalg import det,svd,norm
from numpy.random import randn

In [ ]:
C = randn(3,100); c_avg = np.average(C,axis=1)
C = C-np.outer(c_avg,np.ones(100)); c_avg = np.average(C,axis=1)
print('Is centered?:',c_avg)

Is centered?: [ 5.55111512e-18  2.44249065e-17 -3.30291350e-17]


*Apply affine transformation*

Now we have two clouds: input $C\inm{3}{100}$ and output $C'\inm{3}{100}$.

In [ ]:
Cp = s*np.dot(R,C)+np.outer(b,np.ones(100))

*Implement explicit solution of Procrustes problem*

In [ ]:
U,Sigma,Vt = svd(np.dot(Cp,C.T))
R_star = np.dot(U,Vt)
s_star = np.sum(Sigma)/np.sum(C*C)
b_star = np.average(Cp,axis=1)

*Verify recovered parameters of the transformation*

In [ ]:
print('R-R_star:',R-R_star)
print('error for rotation matrix ||R-R_star||:',norm(R-R_star))
print('error for scale = |s-s_star|:',abs(s-s_star))
print('error for shift = ||b-b_star||:',norm(b-b_star))

R-R_star: [[-3.33066907e-16 -2.77555756e-16 -5.33515388e-16]
 [ 2.77555756e-16 -2.22044605e-16 -3.09730311e-16]
 [ 5.83790142e-16 -4.77651661e-16 -2.22044605e-16]]
error for rotation matrix ||R-R_star||: 1.1459271999146245e-15
error for scale = |s-s_star|: 4.440892098500626e-16
error for shift = ||b-b_star||: 3.194074993567901e-16


*Use the function `generalProcrustes`*

In [ ]:
R_star,s_star,b_star = generalProcrustes(Cp,C)

*and verify ...*

In [ ]:
print('R-R_star:',R-R_star)
print('error for rotation matrix ||R-R_star||:',norm(R-R_star))
print('error for scale = |s-s_star|:',abs(s-s_star))
print('error for shift = ||b-b_star||:',norm(b-b_star))

R-R_star: [[-3.33066907e-16 -2.77555756e-16 -5.33515388e-16]
 [ 2.77555756e-16 -2.22044605e-16 -3.09730311e-16]
 [ 5.83790142e-16 -4.77651661e-16 -2.22044605e-16]]
error for rotation matrix ||R-R_star||: 1.1459271999146245e-15
error for scale = |s-s_star|: 4.440892098500626e-16
error for shift = ||b-b_star||: 3.143025211835776e-16


**End of Solution**

#####**Q4T** (D.1)
Let the cloud $C'=RC$ be created by the rotation with matrix $R=[r_x,r_y,r_z]$, i.e. $\tp{R}R=I_n,$ $\det{R}=1$. We modify the transformation by swapping two columns of $R$, getting the matrix $R'\eqd[r_y,r_x,r_z].$ Is it true that $R`$ is the rotation matrix?

**Answer:**

When we swap two columns of an orthogonal matrix R, it changes the order of the columns, but it does not affect the orthogonality of the matrix. In other words, the resulting matrix R'=[ry,rx,rz] is still orthogonal.

However, a matrix R is also a rotation matrix if its determinant det(R) equals 1.

When we swap two columns of a rotation matrix R, the determinant changes sign, i.e., det(R') = -det(R), and therefore, R' is not a rotation matrix anymore.

#####**Q4T** (D.2)
Let $C\inm{3}{100}$ be a cloud of $n=100$ points in 3D space generated  randomly according to the standard normal distribution. We make a rotation, scaling, and translation (shift) according the following formula: 
$$
c'_i = 
3\cdot
\left[
\begin{array}{ccc}
-\frac{1}{2} & \frac{\sqrt{3}}{2} &  0\\
\frac{\sqrt{3}}{2} & \frac{1}{2} & 0\\
0 & 0 & 1
\end{array}
  \right]
  c_i +
\left[
\begin{array}{c}
1\\
0\\
-1
\end{array}
  \right],\ i=0,\dots,99
$$ 
Note that the above transformation is not rotation. Apply the Procrustes formulas for the clouds $C,C'$. Have you recovered the above transformation? 

**Solution:**

In [ ]:
# Generating random cloud C
np.random.seed(123)
C = np.random.randn(3, 100)

# Applying transformation to get C'
R = np.array([[-1/np.sqrt(2), 1/np.sqrt(2), 0],
              [-1/np.sqrt(6), -1/np.sqrt(6), 2/np.sqrt(6)],
              [1/np.sqrt(3), 1/np.sqrt(3), 1/np.sqrt(3)]])
s = 3
b = np.array([[1], [-1], [0]])
C_prime = s * np.dot(R, C) + b

# Applying Procrustes formulas
R_est, s_est, b_est = generalProcrustes(C_prime, C)

# Printing the estimated rotation matrix, scaling factor, and translation vector
print("Estimated rotation matrix:\n", R_est)
print("\nEstimated scaling factor:", s_est)
print("\nEstimated translation vector:\n", b_est)

Estimated rotation matrix:
 [[-0.70485724  0.70906228 -0.02017315]
 [-0.41551134 -0.38966387  0.82189561]
 [ 0.57491443  0.58770124  0.56928082]]

Estimated scaling factor: 3.0155810571421764

Estimated translation vector:
 [ 9.94658012e-01 -9.95504144e-01 -7.18371480e-04]


As we can see, the estimated rotation matrix R_est is not the same as the original rotation matrix R. This is because the original transformation is not a rotation, but a combination of rotation, scaling, and translation. However, the estimated transformation does recover the scaling factor and translation vector of the original transformation.

#####**Q4T** (D.3)
Suppose, the points of cloud $C'$ are observed with measurement error of normal distribution with $\sigma=3$. Then Procrustes reconstruction of rotation matrix differs in Frobenius norm by about $0.3:$ $\|R-R^*\|_F\approx 0.3$. Is it true?

**Answer:** Yes It's True

**Experiment:**

In [ ]:
# Generating random cloud C
C = np.random.randn(3, 100)

# Applying transformation to get C'
R = np.array([[-1/np.sqrt(2), 1/np.sqrt(2), 0],
              [-1/np.sqrt(6), -1/np.sqrt(6), 2/np.sqrt(6)],
              [1/np.sqrt(3), 1/np.sqrt(3), 1/np.sqrt(3)]])
s = 3
b = np.array([[1], [-1], [0]])
C_prime = s * np.dot(R, C) + b

# Adding measurement error to C'
sigma = 3
C_prime += np.random.normal(scale=sigma, size=C_prime.shape)

# Applying Procrustes formulas
R_est, s_est, b_est = generalProcrustes(C_prime, C)

# Printing the estimated rotation matrix, scaling factor, and translation vector
print("Estimated rotation matrix:\n", R_est)
print("\nEstimated scaling factor:", s_est)
print("\nEstimated translation vector:\n", b_est)

# Calculating the Frobenius norm between R and R_est
f_norm = np.linalg.norm(R - R_est, 'fro')
print("\nFrobenius norm between R and R_est:", f_norm)

Estimated rotation matrix:
 [[-0.6429033   0.75255321  0.14261491]
 [-0.35815834 -0.45995003  0.81250758]
 [ 0.67705092  0.47128509  0.5652366 ]]

Estimated scaling factor: 3.1013449524970116

Estimated translation vector:
 [ 1.06680645 -1.3440132  -0.12862012]

Frobenius norm between R and R_est: 0.23035026662024488


####*Proof of the generalized Procrustes theorem*

*Initial observations:*<br>
The minimization problem of error function  $\cl{E}(R,s,b)\eqd\ds\min_{s,R,b}\left\|sRC+b\tp{1}_N-C'\right\|^2$ dla $C,C'\inm{M}{N}$, can be reduced in few steps to the simpler problem $\min_{s,R}\left\|A-sRB\right\|^2$:
1. Let us notice that at the fixed  parameters $s,R$, the optimal vector $b$ minimizes the squared error for the set of points which are stored in the columns of the matrix $C'-sRC$. 
$$
b^{\ast}=\arg\min_b\|C'-sRC-b\tp{1}_N\|^2 = \arg\min_b\sum_{i\in[N]}\|(c'_i-sRc_i)-b\|^2 \lra
b^{\ast}=\frac{1}{N}\sum_{i\in[N]} (c'_i-sRc_i) = \ov{c}'-sR\ov{c}
$$
Therefore the optimal solution  $b$ must be the centroid this point set, i.e.  $b^{\ast} = \ov{c}'-sR\ov{c}$.
2. Replacing in the formula for the error function $\cl{E}$ the parameter $b$ by its optimal form expressed wrt to $s,R$, we define matrices $A,B$, as follows: 
$$
\begin{array}{l}
b = \ov{c}'-sR\ov{c},\ 
A \eqd C'-\ov{c}'\tp{1}_N,\ 
B \eqd C-\ov{c}\tp{1}_N\\[2pt] 
\lra \cl{E}(R,s,b) = \left\|sRC+b\tp{1}_N-C'\right\|^2 = \left\|A-sRB\right\|^2
\end{array}
$$

*The main part of the proof:*<br>
1. The norm via the *trace* operator:
$$\|A-sRB\|_F^2=\tr{A\tp{A}}+s^2\cdot\tr{B\tp{B}}-2s\cdot\tr{A\tp{B}\tp{R}}$$
*Note:*  The factor two at the above third term follows from the basic properties of trace and transposition operators:
$$
\begin{array}{l}
\tr{(X-Y)\tp{(X-Y)}} = \tr{X\tp{X}}+\tr{Y\tp{Y}}-(\tr{X\tp{Y}}+\tr{Y\tp{X}})\\[3pt]
\tp{(X\tp{Y})}=Y\tp{X} \lra \tr{Y\tp{X}}=\tr{X\tp{Y}} \lra
(\tr{X\tp{Y}}+\tr{Y\tp{X}}) = 2\cdot\tr{X\tp{Y}}
\end{array}
$$
where $X\eqd A,\ Y\eqd sRB.$<br>
The basic properties of trace and transposition which were used above are as follows for any matrices $S,T\inm{M}{M}$:
$$
\tr{S\pm T} = \tr{S}\pm \tr{T},\ \tr{\tp{S}}=\tr{S}
$$
1. The equivalent *trace* problem (at the fixed $s\in\bb{R}_+$):
$$R^*=\arg\max_{R:\tp{R}R=I_m}\tr{A\tp{B}\tp{R}}$$
1. The SVD decomposition : $$A\tp{B}\xeq{svd}{U\Sigma \tp{V}}$$
1. The orthonormal matrix $Z\eqd \tp{V}\tp{R}U:$
$$\tr{A\tp{B}\tp{R}}=\tr{U\Sigma \tp{V}\tp{R}}=\tr{\Sigma \tp{V}\tp{R}U} =\tr{\Sigma Z}$$
*Note:* In the second equality the moving of the matrix $U$ from the first position to the last position follows from the property  $\tr{XY}=\tr{YX}$ which is true only for the matrices $X,Y\inm{M}{M}$, where in this case $X\eqd U,\ Y\eqd\Sigma \tp{V}\tp{R} \lra X,Y\inm{M}{M}$
1. The upper bound:
$$|Z_{ij}|\leq 1 \lra \tr{\Sigma Z}=\sum_i\sigma_i Z_{ii}\leq \sum_i\sigma_i.$$
1. *Conclusion 1*<br>
$R=U\tp{V} \lra Z=I_m$ leads to the maximum value of  $\tr{\Sigma Z}= \tr{A\tp{B}\tp{R}}$ and then for $s\in\bb{R}_+$ the expression  $\|A-sRB\|_F^2$ gets the minimal value equal to:
$$\tr{A\tp{A}}+s^2\cdot\tr{B\tp{B}}-2s\cdot\tr{\Sigma}$$
1. *Conclusion 2*<br>
The minimal value of modelling error $\|A-sR^{\ast}B\|_F^2$ is achieved for the scaling coefficient: $$s^{\ast}=\frac{\tr{\Sigma}}{\tr{B\tp{B}}}$$

$\Box$
